version: "3"

services:
  app:
    image: igor972/php-study
    restart: always
    ports:
      - 5001:80
    volumes:
      - ./:/var/www/html
    stdin_open: true
    tty: true
    depends_on:
      - db
    links:
      - db
  db:
    image: mariadb:10.4
    restart: always
    environment:
      - MARIADB_USER=root
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_DATABASE=datagym
    ports:
      - 3306:3306
    volumes:
      - ./db_data:/var/lib/mysql
